# This docker compose file starts processes on remote aws instances
# For this, docker needs to be in swarm mode with the following nodes
# - engine
# - rabbitmq
# - client
# - mongodb
# - ethereum
#  To work properly the ethereum node and other services might have
# to be removed and simply working with external services

version: '3'
services:
  ethereum:
    image: ethereum/client-go
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "ethereum_root:/root/.ethereum"
    environment:
      - AMP_MAINNET_ETHERBASE
    command: [
      "--port", "30303",
      "--syncmode", "fast",
      "--cache", "1024",
      "--datadir", "/root/.ethereum",
      "--wsapi", "admin,eth,net,web3,personal",
      "--rpcapi", "admin,eth,net,web3,personal",
      "--rpc", "--rpcport", "8545", "--rpcaddr", "0.0.0.0",
      "--ws", "--wsport", "8546", "--wsaddr", "0.0.0.0",
      "--wsorigins", "*",
      "--etherbase", $AMP_MAINNET_ETHERBASE,
      "--rpccorsdomain", "*",
    ]
    networks:
      amp-production:
        aliases:
        - ethereum
    deploy:
      placement:
        constraints:
          - node.hostname == ethereum-production
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      amp-production:
        aliases:
        - rabbitmq
    volumes:
      - "rabbitmq_logs:/var/log/rabbitmq"
      - "rabbitmq_data:/var/lib/rabbitmq"
    deploy:
      placement:
        constraints:
          - node.hostname == rabbitmq-production
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      amp-production:
        aliases:
        - mongodb
    volumes:
    - "mongodb_data:/data/db"
    deploy:
      placement:
        constraints:
          - node.hostname == mongodb-production
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  client:
    image: proofsuite/amp-client:latest
    ports:
      - "80:80"
    environment:
      - AMP_ENGINE_HTTP_URL=/engine
      - AMP_ETHEREUM_NODE_HTTP_URL=/ethereum
      - AMP_ENGINE_WS_URL=ws://${AMP_MAINNET_MATCHING_ENGINE_IP}:8081
      - AMP_ETHEREUM_NODE_WS_URL=wss://mainnet.infura.io/_ws
      - AMP_ETHEREUM_NETWORK_ID=4
    depends_on:
      - matching-engine
      - ethereum
    networks:
      amp-production:
        aliases:
        - client
    deploy:
      placement:
        constraints:
          - node.hostname == client-production
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    command: >
         bin/sh -c "sleep 10 && chmod +x ./replace.sh && sleep 1 && ./replace.sh && cat /usr/share/nginx/html/env.js && nginx -g 'daemon off;'"


  matching-engine:
    image: proofsuite/amp-matching-engine:latest
    ports:
      - '8081:8081'
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      # - AMP_ETHEREUM_NODE_HTTP_URL=http://ethereum:8545
      # - AMP_ETHEREUM_NODE_WS_URL=ws://ethereum:8546
      - AMP_ETHEREUM_NODE_HTTP_URL=https://mainnet.infura.io
      - AMP_ETHEREUM_NODE_WS_URL=wss://mainnet.infura.io/_ws
      - AMP_MONGODB_URL=mongodb
      - AMP_MONGODB_DBNAME=proofdex
      - AMP_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - AMP_EXCHANGE_CONTRACT_ADDRESS=${AMP_MAINNET_EXCHANGE_CONTRACT_ADDRESS}
      - AMP_WETH_CONTRACT_ADDRESS=${AMP_MAINNET_WETH_CONTRACT_ADDRESS}
      - AMP_FEE_ACCOUNT_ADDRESS=${AMP_MAINNET_FEE_ACCOUNT_ADDRESS}
    networks:
      amp-production:
        aliases:
        - matching-engine
    deploy:
      placement:
        constraints:
          - node.hostname == matching-engine-production
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s


networks:
  amp-production:
    external: true

volumes:
  ethereum_root:
  rabbitmq_logs:
  rabbitmq_data:
  mongodb_data:
